In [7]:
import torch
import torch.nn as nn
# https://zhuanlan.zhihu.com/p/458373836
w = torch.arange(2., 20.).view(6, 3)
print(w)
nn.init.xavier_normal_(w)
print(w)

tensor([[ 2.,  3.,  4.],
        [ 5.,  6.,  7.],
        [ 8.,  9., 10.],
        [11., 12., 13.],
        [14., 15., 16.],
        [17., 18., 19.]])
tensor([[-0.1241,  0.2696, -0.0754],
        [-0.1250,  0.0341,  0.1130],
        [-0.5318,  0.1804, -0.0492],
        [-0.7025,  0.0473,  0.7242],
        [ 0.5382,  0.0426, -0.3197],
        [-0.1888, -0.3709,  0.3427]])


In [11]:
m = nn.Linear(20, 10)
type(m.weight.data)

torch.Tensor

In [13]:
x = torch.arange(5.)
print(x)
x.uniform_(-1.0, 1.0)
print(x)

tensor([0., 1., 2., 3., 4.])
tensor([ 0.9312, -0.0896,  0.0660,  0.3706,  0.0282])


In [ ]:
#default neat-style init
def weight_init_default(m):
    if isinstance(m, nn.Linear) or isinstance(m,nn.Conv2d):
        m.weight.data.uniform_(-1.0,1.0)

#xavier initialization (apparently better than pytorch default)
def weight_init_xavier(m): 
    #print "xavier init."
    if isinstance(m, nn.Linear) or isinstance(m,nn.Conv2d):
        size = m.weight.size()
        fan_out = size[0] # number of rows, `fan_out` is the number of output units in the weight tensor.
        fan_in = np.prod(size[1:]) # number of columns, `fan_in` is the number of input units in the weight tensor.
        variance = np.sqrt(2.0/(fan_in + fan_out))
        m.weight.data.normal_(0.0, variance)